# @package eval.bioun_v2.metrics.RGU_def_v2
defaults:
  - .@pre_compute.RGU_forget_gen_v2: RGU_forget_gen_v2
  - .@pre_compute.RGU_retain_gen_v2: RGU_retain_gen_v2

pre_compute:
  RGU_forget_gen_v2:
    access_key: forget_gen
  RGU_retain_gen_v2:
    access_key: retain_gen

handler: def_score
rouge_threshold: 0.5
