# @package eval.bioun_v2.metrics.RGU_retain_gen_v2
defaults:
  - ../../data/datasets@datasets: BioUnlearn_RGU_retain_v2
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.bioun_v2.batch_size}
datasets:
  BioUnlearn_RGU_retain_v2:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset:
    args:
      padding_side: left
