# @package eval.bioun_pac.metrics.PAC_forget_gen
defaults:
  - ../../data/datasets@datasets: BioUnlearn_PAC_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default

handler: rouge
rouge_type: rougeL_recall
batch_size: ${eval.bioun_pac.batch_size}
datasets:
  BioUnlearn_PAC_forget:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset:
    args:
      padding_side: left
