# @package eval.bioun_pac.metrics.RGU_fa_pac
defaults:
  - .@pre_compute.RGU_forget_gen_pac: RGU_forget_gen_pac

pre_compute:
  RGU_forget_gen_pac:
    access_key: forget_gen

handler: fa_score
rouge_threshold: 0.5
