"""
Stage D, PAC-only. Builds train/val/test splits for the PAC scenario ONLY,
writing exclusively to data/splits/PAC_*.jsonl. Deliberately does not touch
RGU_*.jsonl or IFE_*.jsonl -- those are frozen pilot files that every
GA/NPO/RMU/OGDA/RAG-suppression/ROME baseline result in this project depends
on for comparability, and must never be regenerated by an automated script.
"""

import json
import os
import random

random.seed(42)

FILTERED_PATH = "data/filtered/PAC_passed.jsonl"
SPLITS_DIR = "data/splits"


def load_jsonl(path):
    with open(path) as f:
        return [json.loads(l) for l in f]


def make_splits(instances, train=0.60, val=0.20):
    # PAC instances are independently synthetic (no shared concept graph),
    # so a simple instance-level shuffle-split is appropriate (no leakage
    # risk the way multi-instance-per-UMLS-concept RGU/IFE data has).
    shuffled = instances[:]
    random.shuffle(shuffled)
    n = len(shuffled)
    n_train = max(1, int(n * train))
    n_val = max(1, int(n * val))
    return shuffled[:n_train], shuffled[n_train : n_train + n_val], shuffled[n_train + n_val :]


def main():
    assert not os.path.exists(f"{SPLITS_DIR}/PAC_train.jsonl"), (
        "PAC_train.jsonl already exists -- refusing to silently overwrite, "
        "delete it first if you really want to regenerate."
    )

    instances = load_jsonl(FILTERED_PATH)
    print(f"Loaded {len(instances)} passed PAC instances")

    train, val, test = make_splits(instances)
    for name, split in [("train", train), ("val", val), ("test", test)]:
        path = f"{SPLITS_DIR}/PAC_{name}.jsonl"
        with open(path, "w") as f:
            for inst in split:
                f.write(json.dumps(inst) + "\n")
        print(f"  {name}: {len(split)} -> {path}")

    print(f"\nTotal PAC: {len(instances)}")
    print("RGU/IFE splits untouched (this script only ever reads/writes PAC_*.jsonl).")


if __name__ == "__main__":
    main()
